// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFseF2gtEFuK-p9e7d5p5cpjQQzErYYmo',
    appId: '1:67072385828:web:b914b8022b34d7e20b49b1',
    messagingSenderId: '67072385828',
    projectId: 'fir-flutter-auth-a6e6f',
    authDomain: 'fir-flutter-auth-a6e6f.firebaseapp.com',
    storageBucket: 'fir-flutter-auth-a6e6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChtDH8o8hCFoCLfQFFm-ihkqjPCrfmpBc',
    appId: '1:67072385828:android:f680b958d10cf9dd0b49b1',
    messagingSenderId: '67072385828',
    projectId: 'fir-flutter-auth-a6e6f',
    storageBucket: 'fir-flutter-auth-a6e6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGJxZo1GKserKMY5gXBFRHGCy6zZQKcqM',
    appId: '1:67072385828:ios:39826dc0fb7e02960b49b1',
    messagingSenderId: '67072385828',
    projectId: 'fir-flutter-auth-a6e6f',
    storageBucket: 'fir-flutter-auth-a6e6f.appspot.com',
    androidClientId: '67072385828-ltk0vm87kiohn4d6ucl5k4tnh2ei601s.apps.googleusercontent.com',
    iosClientId: '67072385828-qibmmem0uqvb4vp9me4rgo10g37ohg1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
